config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pets#index"
  resources :pets
  resources :diaries, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :grows, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :date,               presence: true
  validates :text,               presence: true
  validates :image,              presence: true
end

app/models/grow.rb
class Grow < ApplicationRecord
  validates :height,           presence: true
  validates :weight,           presence: true
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :name,               presence: true
  validates :sex,                presence: true
  validates :type_of_pet,        presence: true
  validates :birthday,           presence: true
  validates :color,              presence: true
  validates :hospital,           presence: true
  validates :medical_history,    presence: true
  validates :medicine,           presence: true
  validates :allergies,          presence: true
  validates :image,              presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,    presence: true
  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @diary = Diary.new
  end
  
  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to diaries_path
    else 
      render :new
    end
  end

  def index
    @diary = Diary.all
    @diary = Diary.order("created_at DESC")
  end

  def edit
    @diary = Diary.find(params[:id])
    unless user_signed_in?
      redirect_to diaries_path
    end
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to diaries_path
    else render :edit
    end
  end

  def destroy
    diary = Diary.find(params[:id])
    if diary.destroy
    redirect_to diaries_path
    end
  end

  private
  def diary_params
    params.require(:diary).permit(:date, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/grows_controller.rb
class GrowsController < ApplicationController
    
  def index
    @grow = Grow.all
  end 

  def new
    @grow = Grow.new
  end
  
  def create
    @grow = Grow.new(grow_params)
    if @grow.save
      redirect_to root_path
    else 
      render :new
    end
  end
  
  private
    def grow_params
      params.require(:grow).permit(:weight, :height).merge(pet_id: params[:pet_id])
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to root_path
    else 
      render :new
    end
  end

  def show
    @pet =Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path
    else render :edit
    end
  end

  def destroy
    pet = Pet.find(params[:id])
    if pet.destroy
    redirect_to root_path
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :sex, :type_of_pet, :birthday, :color, :hospital, :medical_history, :medicine, :allergies, :walk_time, :character, :type_of_foods, :number_of_meals, :amount_of_food, :memo, :image).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/diaries/_diary.html.erb
<div class="p"></div>
<div class="diary-cards">
  <%= link_to image_tag(diary.image, class: :diarycard__img )%>
  <div class="card-detail">
    <div class="card__date">
      <%= diary.date %>
    </div>
    <div class="text">
      <%= diary.text %>
  </div>
</div>
        <div class="diary__manage">
          <div class="diary_edit">
            <%= link_to "編集", edit_diary_path(diary.id) %>
          </div>
          <div class="diary_delete">
            <%= link_to "削除",diary_path(diary.id), method: :delete %>
          </div>
        </div>
</div>
<div class="p"></div>

app/views/diaries/_form.html.erb
  <%= form_with model: diary, local: true do |f|%>
    <div class="field">
      <%= f.date_field :date, class:"field" %>
    </div>

    <div class="field">
      <%= f.label :text, "*テキスト(130字以内)" %><br />
      <%= f.text_area :text, id:"diary-text" %>
    </div>

    <div class="field">
      <%= f.label :image, "*写真" %><br />
      <%= f.file_field :image, id:"diary-image" %>
    </div>

    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  <% end %>

app/views/diaries/edit.html.erb
<div class="form-main">
  <div class="form__wrapper">
      <h2 class="page-heading">日記</h2>
        <%= render partial: "form", locals: { diary: @diary } %>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<main class="main-diary">
  <div class="inner_head">
  </div>
  <div class="inner">
    <div class="diary-card__wrapper">
      <%= render partial: 'diary', collection: @diary %>
    </div>
  </div>
</main>

app/views/diaries/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Diary</h2>
        <%= render partial: "form", locals: { diary: @diary } %>
    </div>
  </div>
</div>

app/views/grows/_form.html.erb
  <%= form_with model: grow, local: true do |f|%>
    
    <div class="field">
      <%= f.label :height, "身長" %><br />
      <%= f.text_field :height, id:"grow-text" %>
    </div>

    <div class="field">
      <%= f.label :grow, "体重" %><br />
      <%= f.text_field :grow, id:"grow-text" %>
    </div>

    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  <% end %>

app/views/grows/edit.html.erb
<h4> プロフィール編集</h4>

<%= render 'form', profile: @profile %>

app/views/grows/index.html.erb
<div class='col-md-8'>
      <div class='card-body'>
        <h5 class='card-title'>[Current_Profile]</h5>
          <p>身長: <%= @grow.height  %></p>
            <%= link_to '体重を入力してください','grows/new' %>
      </div>
    </div>
  </div>

<div class = 'box'>
  <a class='btn-floating halfway-fab waves-effect waves-light red', href='profiles/<%= @grow.id %>/grows/new' ><i class='material-icons'>+</i></a>
</div>
<%= line_chart Weight.group_by_day(:updated_at).average(:weight), messages: {empty: 'No data'} %>

app/views/grows/new.html.erb
<div class="form-main">
  <div class="form__wrapper">
      <h2 class="page-heading">身長.体重</h2>
        <%= render partial: "form", locals: { grow: @grow } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My sweeties</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__btn, method: :delete %>
              <%= link_to "Petを追加する", new_pet_path, class: :nav__btn %>
              <%= link_to "日記を書く", new_diary_path, class: :nav__btn %>
             </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Sweeties All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: pet, local: true do |f|%>
  <div class="field">
    <%= f.label :name, "*お名前" %><br />
    <%= f.text_field :name, id:"pet_name" %>
  </div>

  <div class="field">
    <%= f.label :sex, "*性別" %><br />
    <%= f.text_field :sex, id:"pet_sex" %>
  </div>

  <div class="field">
    <%= f.label :type_of_pet, "*種類" %><br />
    <%= f.text_field :type_of_pet, id:"pet_type_of_pet" %>
  </div>

  <div class="field">
    <%= f.label :birthday, "*お誕生日" %><br />
    <%= f.text_field :birthday, id:"pet_birthday" %>
  </div>

  <div class="field">
    <%= f.label :color, "*色" %><br />
    <%= f.text_field :color, id:"pet_color" %>
  </div>

  <div class="field">
    <%= f.label :hospital, "*かかりつけの病院" %><br />
    <%= f.text_area :hospital, id:"pet_hospital" %>
  </div>

  <div class="field">
    <%= f.label :medical_history, "*病歴" %><br />
    <%= f.text_area :medical_history, id:"pet_medical_history" %>
  </div>

  <div class="field">
    <%= f.label :medicine, "*服用中のお薬" %><br />
    <%= f.text_area :medicine, id:"pet_medicine" %>
  </div>

  <div class="field">
    <%= f.label :allergies, "*アレルギー" %><br />
    <%= f.text_area :allergies, id:"pet_allergies" %>
  </div>

  <div class="field">
    <%= f.label :walk_time, "お散歩時間" %><br />
    <%= f.text_field :walk_time, id:"pet_walk_time" %>
  </div>

  <div class="field">
    <%= f.label :character, "ペットの性格" %><br />
    <%= f.text_area :character, id:"pet_character" %>
  </div>

  <div class="field">
    <%= f.label :type_of_foods, "ご飯の種類" %><br />
    <%= f.text_field :type_of_foods, id:"pet_type_of_foods" %>
  </div>

  <div class="field">
    <%= f.label :number_of_meals, "１日のご飯の回数" %><br />
    <%= f.text_field :number_of_meals, id:"pet_number_of_meals" %>
  </div>

  <div class="field">
    <%= f.label :amount_of_food, "一回のご飯の量" %><br />
    <%= f.text_field :amount_of_food, id:"pet_amount_of_food" %>
  </div>

  <div class="field">
    <%= f.label :memo, "Memo" %><br />
    <%= f.text_area :memo, id:"pet_memo" %>
  </div>

  <div class="field">
    <%= f.label :image, "*ペットのプロフィール写真" %><br />
    <%= f.file_field :image, id:"pet_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div class="card">
  <%= link_to image_tag(pet.image, class: :card__imgs ), pet_path(pet.id)%>
  <div class=" card__body">
    <%= link_to pet.name, pet_path(pet.id), class: :card__title%>  
  </div>
</div>

app/views/pets/edit.html.erb
<div class="form-main">
  <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: "form", locals: { pet: @pet } %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<main class="main">
  <div class="inner">
    <div class="card__wrapper">
      <%= render partial: 'pet', collection: @pets %>
    </div>
  </div>
</main>

app/views/pets/new.html.erb
<div class="form-main">
  <div class="form__wrapper">
    <h2 class="form-heading">ペットの情報</h2>
      <h5 class="form-notice">*のついた箇所は記入必須です</h5>
    <%= render partial: "form", locals: { pet: @pet } %>
  </div>
</div>

app/views/pets/show.html.erb
<main class="main">
  <div class="pet--wrapper">
    <div class="pet-image-card">
      <div class="pet-card">
        <div class="pet__image">
          <%= image_tag @pet.image %>
        </div>
        <div class="pet--profile">
          <div class="pet-profile">

            <div class="pet--tag">
              Profile
            </div>
            <p class="pet__heading">
              <%= @pet.name %>
            </p>
          
          <div class="pet__detail">
            <p class="detail__title">性別</p>
            <p class="detail__message">
              <%= @pet.sex %>
            </p>
          </div>

          <div class="pet__detail">
            <p class="detail__title">種類</p>
            <p class="detail__message">
              <%= @pet.type_of_pet %>
            </p>
          </div>

          <div class="pet__detail">
            <p class="detail__title">お誕生日</p>
            <p class="detail__message">
              <%= @pet.birthday %>
            </p>
          </div>

          <div class="pet__detail">
            <p class="detail__title">色</p>
            <p class="detail__message">
              <%= @pet.color %>
            </p>
          </div>
        </div>
        </div>

        <div class="pet-health">
          <div class="pet--tag">
            Health
          </div>
          <div class="pet__detail">
            <p class="detail__title">かかりつけの病院</p>
            <p class="detail__message">
              <%= @pet.hospital %>
            </p>
          </div>

          <div class="pet__detail">
            <p class="detail__title">病歴</p>
            <p class="detail__message">
              <%= @pet.medical_history %>
            </p>
          </div>
          
          <div class="pet__detail">
            <p class="detail__title">服用中のお薬</p>
            <p class="detail__message">
              <%= @pet.medicine %>
            </p>
          </div>

          <div class="pet__detail">
            <p class="detail__title">アレルギー</p>
            <p class="detail__message">
              <%= @pet.allergies %>
            </p>
          </div>
        </div>
      
        <div class="pet-care">
          <div class="pet--tag">
            Care
          </div>
          <div class="pet__detail">
            <p class="detail__title">お散歩時間</p>
            <p class="detail__message">
              <%= @pet.walk_time %>
            </p>
          </div>
          
          <div class="pet__detail">
            <p class="detail__title">ペットの性格</p>
            <p class="detail__message">
              <%= @pet.character %>
            </p>
          </div>
          <div class="pet__detail">
            <p class="detail__title">ご飯の種類</p>
            <p class="detail__message">
              <%= @pet.type_of_foods %>
            </p>
          </div>
          <div class="pet__detail">
            <p class="detail__title">１日のご飯の回数</p>
            <p class="detail__message">
              <%= @pet.number_of_meals %>
            </p>
          </div>
          <div class="pet__detail">
            <p class="detail__title">一回のご飯の量</p>
            <p class="detail__message">
              <%= @pet.amount_of_food %>
            </p>
          </div>
        </div>

        <div class="pet-memo">
          <div class="pet--tag">
            Memo
          </div>
          <div class="pet__detail">
            <p class="detail__title"></p>
            <p class="detail__message">
              <%= @pet.memo %>
            </p>
          </div>
        </div>

    
          <div class="pet_btn">
            <div class="pet__btn">
              <div class="pet___btn">
                <%= link_to "EDIT", edit_pet_path(@pet.id) %>
              </div>
              <div class="pet___btn">
                <%= link_to "DELETE", pet_path(@pet.id), method: :delete %>
              </div>
              <div class="pet___btn">
                <%= link_to "GROW", new_grow_path %>
              </div>
              <div class="pet___btn">
                <%= link_to "DIARY", diaries_path %>
              </div>
            </div>
          </div>
          <div class="p"></div> 
       </div>
      </div>
    </div>
  </div>
</main>